# Generated by Django 5.2.10 on 2026-01-15 16:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(help_text='虚拟卡号，加密存储', max_length=20, verbose_name='卡号')),
                ('card_holder', models.CharField(max_length=100, verbose_name='持卡人姓名')),
                ('expiry_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='过期月份')),
                ('expiry_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2024), django.core.validators.MaxValueValidator(2099)], verbose_name='过期年份')),
                ('cvv', models.CharField(help_text='加密存储', max_length=4, verbose_name='CVV安全码')),
                ('pool_type', models.CharField(choices=[('public', '公共卡池'), ('private', '私有卡池')], db_index=True, default='public', max_length=20, verbose_name='卡池类型')),
                ('status', models.CharField(choices=[('available', '可用'), ('in_use', '使用中'), ('used', '已使用'), ('invalid', '无效'), ('expired', '已过期')], db_index=True, default='available', max_length=20, verbose_name='卡状态')),
                ('use_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功次数')),
                ('max_use_count', models.IntegerField(default=1, help_text='0表示无限制', verbose_name='最大使用次数')),
                ('billing_address', models.JSONField(blank=True, default=dict, help_text='包含street, city, state, zip, country等', verbose_name='账单地址')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('owner_user', models.ForeignKey(blank=True, help_text='私有卡的所有者，公共卡为空', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_cards', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '虚拟卡',
                'verbose_name_plural': '虚拟卡',
                'db_table': 'cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(help_text='如: Google订阅, SheerID验证', max_length=200, verbose_name='使用目的')),
                ('success', models.BooleanField(db_index=True, default=False, verbose_name='是否成功')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('transaction_id', models.CharField(blank=True, max_length=200, verbose_name='交易ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='人民币', max_digits=10, verbose_name='交易金额(元)')),
                ('currency', models.CharField(default='CNY', max_length=10, verbose_name='货币单位')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='存储响应数据、截图等', verbose_name='额外数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='使用时间')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='cards.card', verbose_name='虚拟卡')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_usages', to='tasks.task', verbose_name='关联任务')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '卡使用记录',
                'verbose_name_plural': '卡使用记录',
                'db_table': 'card_usage_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['pool_type', 'status'], name='cards_pool_ty_4ecf55_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['owner_user', 'status'], name='cards_owner_u_e1edfb_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['status', 'created_at'], name='cards_status_40d69d_idx'),
        ),
        migrations.AddIndex(
            model_name='cardusagelog',
            index=models.Index(fields=['card', 'success'], name='card_usage__card_id_58ab60_idx'),
        ),
        migrations.AddIndex(
            model_name='cardusagelog',
            index=models.Index(fields=['user', 'created_at'], name='card_usage__user_id_cc5c68_idx'),
        ),
        migrations.AddIndex(
            model_name='cardusagelog',
            index=models.Index(fields=['task', 'created_at'], name='card_usage__task_id_ac5da8_idx'),
        ),
    ]
