# Generated by Django 5.2.10 on 2026-01-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='余额'),
        ),
        migrations.AddField(
            model_name='card',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='银行名称'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(default='visa', help_text='如: visa, mastercard, amex', max_length=20, verbose_name='卡类型'),
        ),
    ]
