# Generated by Django 5.2.10 on 2026-01-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_balance_card_bank_name_card_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_holder',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='持卡人姓名'),
        ),
    ]
