# Generated by Django 5.0.1 on 2026-01-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_card_holder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardApiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如: ActCard, OtherProvider', max_length=100, unique=True, verbose_name='配置名称')),
                ('redeem_url', models.URLField(help_text='如: https://actcard.xyz/api/keys/redeem', max_length=500, verbose_name='激活接口URL')),
                ('query_url', models.URLField(blank=True, help_text='如: https://actcard.xyz/api/keys/query', max_length=500, verbose_name='查询接口URL')),
                ('request_method', models.CharField(default='POST', max_length=10, verbose_name='请求方法')),
                ('request_headers', models.JSONField(blank=True, default=dict, help_text='如: {"Authorization": "Bearer xxx"}', verbose_name='请求头')),
                ('request_body_template', models.JSONField(blank=True, default=dict, help_text='使用 {key_id} 作为占位符', verbose_name='请求体模板')),
                ('response_mapping', models.JSONField(blank=True, default=dict, help_text='外部API字段到系统字段的映射', verbose_name='响应字段映射')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('timeout', models.IntegerField(default=30, verbose_name='超时时间(秒)')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '卡密API配置',
                'verbose_name_plural': '卡密API配置',
                'db_table': 'card_api_configs',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
