# Generated by Django 5.0.1 on 2026-01-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_add_card_api_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='key_expire_time',
            field=models.DateTimeField(blank=True, help_text='卡密的有效期限，过期后不可使用', null=True, verbose_name='卡密过期时间'),
        ),
    ]
