# Generated by Django 5.0.1 on 2026-01-26 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('google_accounts', '0005_rename_account_gro_owner_u_a1b2c3_idx_account_gro_owner_u_b1cba0_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudMailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='配置名称')),
                ('api_base', models.URLField(help_text='如: https://mail.180711.xyz/api/public', verbose_name='API地址')),
                ('api_token', models.CharField(max_length=255, verbose_name='API Token')),
                ('domains', models.JSONField(default=list, help_text='如: ["pigll.site", "example.com"]', verbose_name='可用域名')),
                ('default_role', models.CharField(default='user', max_length=50, verbose_name='默认角色')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cloud Mail配置',
                'verbose_name_plural': 'Cloud Mail配置',
                'db_table': 'email_cloudmail_configs',
            },
        ),
        migrations.CreateModel(
            name='RecoveryEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='邮箱地址')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('google_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_email_account', to='google_accounts.googleaccount', verbose_name='绑定的Google账号')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recovery_emails', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '辅助邮箱',
                'verbose_name_plural': '辅助邮箱',
                'db_table': 'email_recovery_emails',
            },
        ),
    ]
