# Generated by Django 5.2.10 on 2026-01-15 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Google邮箱')),
                ('password', models.CharField(help_text='加密存储', max_length=255, verbose_name='密码')),
                ('recovery_email', models.EmailField(blank=True, max_length=254, verbose_name='恢复邮箱')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='绑定手机号')),
                ('two_fa_enabled', models.BooleanField(default=False, verbose_name='是否启用2FA')),
                ('two_fa_secret', models.CharField(blank=True, help_text='加密存储', max_length=255, verbose_name='2FA密钥')),
                ('status', models.CharField(choices=[('active', '正常'), ('locked', '锁定'), ('disabled', '停用'), ('pending_verify', '待验证')], db_index=True, default='pending_verify', max_length=20, verbose_name='账号状态')),
                ('gemini_status', models.CharField(choices=[('not_subscribed', '未订阅'), ('pending', '订阅中'), ('active', '已订阅'), ('expired', '已过期'), ('cancelled', '已取消')], db_index=True, default='not_subscribed', max_length=20, verbose_name='Gemini状态')),
                ('sheerid_verified', models.BooleanField(default=False, verbose_name='是否通过SheerID验证')),
                ('sheerid_link', models.TextField(blank=True, verbose_name='SheerID验证链接')),
                ('card_bound', models.BooleanField(default=False, verbose_name='是否已绑卡')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP')),
                ('subscription_start_date', models.DateField(blank=True, null=True, verbose_name='订阅开始日期')),
                ('subscription_end_date', models.DateField(blank=True, null=True, verbose_name='订阅结束日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('bound_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_accounts', to='cards.card', verbose_name='绑定的虚拟卡')),
                ('owner_user', models.ForeignKey(blank=True, help_text='如果为空则为平台账号池', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='google_accounts', to=settings.AUTH_USER_MODEL, verbose_name='账号所有者')),
            ],
            options={
                'verbose_name': 'Google账号',
                'verbose_name_plural': 'Google账号',
                'db_table': 'google_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeminiSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_plan', models.CharField(default='Advanced', max_length=50, verbose_name='订阅计划')),
                ('start_date', models.DateField(verbose_name='订阅开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='订阅结束日期')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='人民币', max_digits=10, verbose_name='订阅费用(元)')),
                ('success', models.BooleanField(db_index=True, default=False, verbose_name='是否成功')),
                ('error_message', models.TextField(blank=True, verbose_name='失败原因')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='额外数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemini_subscriptions', to='cards.card', verbose_name='使用的虚拟卡')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gemini_subscriptions', to='tasks.task', verbose_name='关联任务')),
                ('google_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gemini_subscriptions', to='google_accounts.googleaccount', verbose_name='Google账号')),
            ],
            options={
                'verbose_name': 'Gemini订阅记录',
                'verbose_name_plural': 'Gemini订阅记录',
                'db_table': 'gemini_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SheerIDVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(help_text='如: student(学生), teacher(教师)', max_length=50, verbose_name='验证类型')),
                ('verification_link', models.TextField(verbose_name='SheerID验证链接')),
                ('submitted_data', models.JSONField(default=dict, help_text='姓名、学校、证件等信息', verbose_name='提交的验证数据')),
                ('verified', models.BooleanField(db_index=True, default=False, verbose_name='是否通过验证')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='通过时间')),
                ('error_message', models.TextField(blank=True, verbose_name='失败原因')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='存储响应数据、截图等', verbose_name='额外数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('google_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheerid_verifications', to='google_accounts.googleaccount', verbose_name='Google账号')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheerid_verifications', to='tasks.task', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': 'SheerID验证记录',
                'verbose_name_plural': 'SheerID验证记录',
                'db_table': 'sheerid_verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='googleaccount',
            index=models.Index(fields=['status', 'gemini_status'], name='google_acco_status_49f373_idx'),
        ),
        migrations.AddIndex(
            model_name='googleaccount',
            index=models.Index(fields=['owner_user', 'status'], name='google_acco_owner_u_8bb473_idx'),
        ),
        migrations.AddIndex(
            model_name='googleaccount',
            index=models.Index(fields=['gemini_status', 'subscription_end_date'], name='google_acco_gemini__226097_idx'),
        ),
        migrations.AddIndex(
            model_name='geminisubscription',
            index=models.Index(fields=['google_account', 'success'], name='gemini_subs_google__9348b1_idx'),
        ),
        migrations.AddIndex(
            model_name='geminisubscription',
            index=models.Index(fields=['task', 'success'], name='gemini_subs_task_id_4bcb28_idx'),
        ),
        migrations.AddIndex(
            model_name='geminisubscription',
            index=models.Index(fields=['success', 'start_date'], name='gemini_subs_success_a3e8a1_idx'),
        ),
        migrations.AddIndex(
            model_name='sheeridverification',
            index=models.Index(fields=['google_account', 'verified'], name='sheerid_ver_google__13af41_idx'),
        ),
        migrations.AddIndex(
            model_name='sheeridverification',
            index=models.Index(fields=['task', 'verified'], name='sheerid_ver_task_id_0774cd_idx'),
        ),
    ]
