# Generated by Django 5.0.1 on 2026-01-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleaccount',
            name='browser_id',
            field=models.CharField(blank=True, help_text='关联的比特浏览器ID', max_length=255, verbose_name='浏览器ID'),
        ),
        migrations.AddField(
            model_name='googleaccount',
            name='browser_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='浏览器名称'),
        ),
        migrations.AddField(
            model_name='googleaccount',
            name='secret_key',
            field=models.CharField(blank=True, help_text='加密存储的密钥', max_length=255, verbose_name='密钥'),
        ),
    ]
