# Generated by Django 5.0.1 on 2026-01-19 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_accounts', '0002_googleaccount_browser_id_googleaccount_browser_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleaccount',
            name='browser_id',
        ),
        migrations.RemoveField(
            model_name='googleaccount',
            name='browser_name',
        ),
        migrations.RemoveField(
            model_name='googleaccount',
            name='secret_key',
        ),
    ]
