# Generated by Django 5.0.1 on 2026-01-25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("google_accounts", "0003_remove_googleaccount_browser_id_and_more"),
    ]

    operations = [
        # 1. 创建 AccountGroup 表
        migrations.CreateModel(
            name="AccountGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="如：售后_10个、2FA_5个",
                        max_length=100,
                        verbose_name="分组名称",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="分组描述")),
                (
                    "account_count",
                    models.PositiveIntegerField(default=0, verbose_name="账号数量"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所有者",
                    ),
                ),
            ],
            options={
                "verbose_name": "账号分组",
                "verbose_name_plural": "账号分组",
                "db_table": "account_groups",
                "ordering": ["-created_at"],
            },
        ),
        # 2. 添加索引
        migrations.AddIndex(
            model_name="accountgroup",
            index=models.Index(
                fields=["owner_user", "name"], name="account_gro_owner_u_a1b2c3_idx"
            ),
        ),
        # 3. 给 GoogleAccount 添加 group 外键
        migrations.AddField(
            model_name="googleaccount",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="账号分组，如：售后分组、2FA分组等",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounts",
                to="google_accounts.accountgroup",
                verbose_name="所属分组",
            ),
        ),
    ]
