# Generated by Django 5.0.1 on 2026-01-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_accounts', '0004_add_account_group'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountgroup',
            new_name='account_gro_owner_u_b1cba0_idx',
            old_name='account_gro_owner_u_a1b2c3_idx',
        ),
    ]
