# Generated by Django 5.2.10 on 2026-01-15 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='专区名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='专区代码')),
                ('description', models.TextField(blank=True, verbose_name='专区描述')),
                ('icon', models.CharField(blank=True, max_length=500, verbose_name='图标URL')),
                ('plugin_class', models.CharField(max_length=200, verbose_name='插件类路径')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('price_per_task', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='每个任务价格')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '专区',
                'verbose_name_plural': '专区',
                'db_table': 'zones_zone',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['code'], name='zones_zone_code_36d670_idx'), models.Index(fields=['is_active'], name='zones_zone_is_acti_ca7736_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserZoneAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('quota_limit', models.IntegerField(default=-1, verbose_name='配额限制')),
                ('quota_used', models.IntegerField(default=0, verbose_name='已使用配额')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_accesses', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='zones.zone', verbose_name='专区')),
            ],
            options={
                'verbose_name': '用户专区权限',
                'verbose_name_plural': '用户专区权限',
                'db_table': 'zones_user_access',
                'indexes': [models.Index(fields=['user'], name='zones_user__user_id_c1dca1_idx'), models.Index(fields=['zone'], name='zones_user__zone_id_ec2a47_idx')],
                'unique_together': {('user', 'zone')},
            },
        ),
        migrations.CreateModel(
            name='ZoneConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(max_length=100, verbose_name='配置键')),
                ('config_value', models.TextField(blank=True, verbose_name='配置值')),
                ('value_type', models.CharField(default='string', max_length=20, verbose_name='值类型')),
                ('description', models.TextField(blank=True, verbose_name='配置说明')),
                ('is_secret', models.BooleanField(default=False, verbose_name='是否敏感信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='zones.zone', verbose_name='专区')),
            ],
            options={
                'verbose_name': '专区配置',
                'verbose_name_plural': '专区配置',
                'db_table': 'zones_config',
                'indexes': [models.Index(fields=['zone'], name='zones_confi_zone_id_bd3040_idx')],
                'unique_together': {('zone', 'config_key')},
            },
        ),
    ]
