# Generated by Django 5.2.10 on 2026-01-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_type', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('socks5', 'SOCKS5')], default='http', max_length=20, verbose_name='代理类型')),
                ('host', models.CharField(max_length=255, verbose_name='代理主机')),
                ('port', models.IntegerField(verbose_name='端口')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='用户名')),
                ('password', models.CharField(blank=True, help_text='加密存储', max_length=255, verbose_name='密码')),
                ('country', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='国家')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='地区')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='城市')),
                ('status', models.CharField(choices=[('active', '可用'), ('inactive', '不可用'), ('testing', '测试中')], db_index=True, default='active', max_length=20, verbose_name='状态')),
                ('response_time', models.FloatField(default=0, verbose_name='响应时间(ms)')),
                ('success_rate', models.FloatField(default=100, verbose_name='成功率(%)')),
                ('use_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('last_check_at', models.DateTimeField(blank=True, null=True, verbose_name='最后检查时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '代理',
                'verbose_name_plural': '代理',
                'db_table': 'proxies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'country'], name='proxies_status_b4aaaa_idx'), models.Index(fields=['status', 'success_rate'], name='proxies_status_57397e_idx')],
            },
        ),
    ]
