// Element Plus icons compatibility layer.
//
// Goal: remove Element Plus icons dependency while minimizing refactors.
// We export the same icon component names used in the codebase, backed by lucide-vue-next.

import {
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BarChart3,
  Bell,
  Box,
  Check,
  ChevronDown,
  CircleCheck,
  Clock,
  Coins,
  CreditCard,
  Download,
  DollarSign,
  FileCheck,
  Grid3X3,
  Home,
  Info,
  Key,
  LayoutGrid,
  Link2,
  List,
  Loader2,
  Lock,
  LogOut,
  Mail,
  MessageCircle,
  PanelLeftClose,
  PanelLeftOpen,
  Pause,
  Pencil,
  Play,
  Plus,
  RefreshCcw,
  RefreshCw,
  RotateCcw,
  Search,
  Settings,
  Star,
  Ticket,
  Trash2,
  TrendingUp,
  Upload,
  User,
  Wallet,
  Wand2,
  XCircle,
  type LucideProps,
} from 'lucide-vue-next'

export type { LucideProps }

// Keep exported names consistent with existing imports.
export {
  Plus,
  User,
  // Element Plus icons used in older docs/snippets.
  MessageCircle as ChatDotRound,
  CreditCard,
  Settings as Setting,
  Grid3X3 as Grid,
  DollarSign as Money,
  RefreshCw as Refresh,
  CircleCheck,
  Coins as Coin,
  Search,
  Upload,
  Key,
  Wallet,
  Trash2 as Delete,
  Pencil as Edit,
  Home as HomeFilled,
  Link2 as Connection,
  BarChart3 as DataAnalysis,
  BarChart3 as DataLine,
  Bell,
  ChevronDown as ArrowDown,
  Box,
  PanelLeftClose as Fold,
  PanelLeftOpen as Expand,
  TrendingUp as TrendCharts,
  List,
  XCircle as CircleClose,
  Info as InfoFilled,
  RotateCcw as RefreshLeft,
  User as UserFilled,
  Ticket as Tickets,
  Mail,
  Clock,
  Check,
  Wand2 as MagicStick,
  Star,
  LogOut as SwitchButton,
  ArrowUp as Top,
  ArrowLeft as Back,
  ArrowRight,
  FileCheck as DocumentChecked,
  Loader2 as Loading,
  LayoutGrid as Platform,
  Play as VideoPlay,
  Pause as VideoPause,
  Lock,
  Download,
}

// Additional icons referenced by existing code paths.
// Some pages use these names as components.
export { RefreshCcw }
