# Generated by Django 5.2.10 on 2026-01-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitBrowserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='比特浏览器配置ID')),
                ('profile_name', models.CharField(max_length=200, verbose_name='配置名称')),
                ('browser_config', models.JSONField(default=dict, help_text='浏览器版本、UA、分辨率等', verbose_name='浏览器配置')),
                ('fingerprint_config', models.JSONField(default=dict, help_text='Canvas、WebGL、音频等指纹信息', verbose_name='指纹配置')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否激活')),
                ('use_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '比特浏览器配置',
                'verbose_name_plural': '比特浏览器配置',
                'db_table': 'bitbrowser_profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
