# Generated by Django 5.2.10 on 2026-01-15 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bitbrowser', '0001_initial'),
        ('google_accounts', '0001_initial'),
        ('proxies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bitbrowserprofile',
            name='google_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitbrowser_profiles', to='google_accounts.googleaccount', verbose_name='关联的Google账号'),
        ),
        migrations.AddField(
            model_name='bitbrowserprofile',
            name='proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitbrowser_profiles', to='proxies.proxy', verbose_name='使用的代理'),
        ),
        migrations.AddField(
            model_name='bitbrowserprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitbrowser_profiles', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddIndex(
            model_name='bitbrowserprofile',
            index=models.Index(fields=['user', 'is_active'], name='bitbrowser__user_id_3b9238_idx'),
        ),
        migrations.AddIndex(
            model_name='bitbrowserprofile',
            index=models.Index(fields=['google_account'], name='bitbrowser__google__402bc4_idx'),
        ),
    ]
