# Generated by Django 5.0.1 on 2026-01-19 14:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbrowser', '0002_initial'),
        ('proxies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100, verbose_name='分组名称')),
                ('bitbrowser_group_id', models.CharField(help_text='对应比特浏览器API中的groupId', max_length=100, unique=True, verbose_name='比特浏览器分组ID')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '浏览器分组',
                'verbose_name_plural': '浏览器分组',
                'db_table': 'bitbrowser_groups',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrowserWindowRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('browser_id', models.CharField(db_index=True, help_text='通过API创建后返回的浏览器ID', max_length=100, unique=True, verbose_name='比特浏览器窗口ID')),
                ('browser_name', models.CharField(max_length=200, verbose_name='窗口名称')),
                ('account_email', models.EmailField(db_index=True, max_length=254, verbose_name='账号邮箱')),
                ('account_password', models.CharField(blank=True, max_length=255, verbose_name='账号密码')),
                ('backup_email', models.EmailField(blank=True, max_length=254, verbose_name='备用邮箱')),
                ('two_fa_secret', models.CharField(blank=True, max_length=100, verbose_name='2FA密钥')),
                ('platform_url', models.URLField(blank=True, verbose_name='平台URL')),
                ('extra_urls', models.TextField(blank=True, help_text='多个URL用逗号分隔', verbose_name='额外URL')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '未活跃'), ('deleted', '已删除')], db_index=True, default='active', max_length=20, verbose_name='状态')),
                ('open_count', models.IntegerField(default=0, verbose_name='打开次数')),
                ('last_opened_at', models.DateTimeField(blank=True, null=True, verbose_name='最后打开时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='windows', to='bitbrowser.browsergroup', verbose_name='所属分组')),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='browser_windows', to='proxies.proxy', verbose_name='使用的代理')),
            ],
            options={
                'verbose_name': '浏览器窗口记录',
                'verbose_name_plural': '浏览器窗口记录',
                'db_table': 'bitbrowser_window_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account_email', 'status'], name='bitbrowser__account_47f144_idx'), models.Index(fields=['group', 'status'], name='bitbrowser__group_i_f5d782_idx'), models.Index(fields=['created_at'], name='bitbrowser__created_ef5b05_idx')],
            },
        ),
    ]
