# Generated by Django 5.2.10 on 2026-01-15 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(db_index=True, help_text='如: sheerid, google, openai', max_length=100, verbose_name='服务名称')),
                ('key_name', models.CharField(help_text='用户自定义的key名称，便于识别', max_length=200, verbose_name='Key名称')),
                ('api_key_encrypted', models.TextField(help_text='加密存储的APIkey', verbose_name='APIkey')),
                ('usage_quota_limit', models.IntegerField(default=0, help_text='0表示无限制', verbose_name='配额上限')),
                ('usage_quota_used', models.IntegerField(default=0, verbose_name='已使用配额')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否激活')),
                ('is_valid', models.BooleanField(default=True, help_text='最近一次验证是否成功', verbose_name='是否有效')),
                ('last_validated_at', models.DateTimeField(blank=True, null=True, verbose_name='最后验证时间')),
                ('validation_error', models.TextField(blank=True, verbose_name='验证错误信息')),
                ('use_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功次数')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='存储服务特定的配置信息', verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '用户APIkey',
                'verbose_name_plural': '用户APIkey',
                'db_table': 'user_api_keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'service', 'is_active'], name='user_api_ke_user_id_653717_idx'), models.Index(fields=['service', 'is_valid'], name='user_api_ke_service_8d4c6c_idx')],
                'unique_together': {('user', 'service', 'key_name')},
            },
        ),
    ]
