# Generated by Django 5.2.10 on 2026-01-15 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(help_text='如: create_account, bind_card, subscribe_gemini', max_length=100, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='任务状态')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '普通'), ('high', '高'), ('urgent', '紧急')], default='normal', max_length=20, verbose_name='优先级')),
                ('progress', models.IntegerField(default=0, help_text='0-100', verbose_name='进度百分比')),
                ('input_data', models.JSONField(default=dict, help_text='任务执行所需的参数', verbose_name='输入数据')),
                ('output_data', models.JSONField(blank=True, default=dict, help_text='任务执行的结果', verbose_name='输出数据')),
                ('error_message', models.TextField(blank=True, help_text='任务失败时的错误详情', verbose_name='错误信息')),
                ('cost_amount', models.DecimalField(decimal_places=2, default=0, help_text='人民币', max_digits=10, verbose_name='消耗金额(元)')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Celery任务ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='存储额外的自定义信息', verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='zones.zone', verbose_name='所属专区')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', '调试'), ('info', '信息'), ('warning', '警告'), ('error', '错误')], db_index=True, default='info', max_length=20, verbose_name='日志级别')),
                ('message', models.TextField(verbose_name='日志消息')),
                ('step', models.CharField(blank=True, help_text='如: login, verify_email, bind_card', max_length=100, verbose_name='执行步骤')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='存储截图路径、响应数据等', verbose_name='额外数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.task', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '任务日志',
                'verbose_name_plural': '任务日志',
                'db_table': 'task_logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='统计日期')),
                ('period_type', models.CharField(choices=[('daily', '日'), ('weekly', '周'), ('monthly', '月')], default='daily', max_length=20, verbose_name='统计周期')),
                ('total_tasks', models.IntegerField(default=0, verbose_name='总任务数')),
                ('success_tasks', models.IntegerField(default=0, verbose_name='成功任务数')),
                ('failed_tasks', models.IntegerField(default=0, verbose_name='失败任务数')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总消耗金额(元)')),
                ('avg_duration', models.FloatField(default=0, verbose_name='平均执行时长(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_statistics', to='zones.zone', verbose_name='专区')),
            ],
            options={
                'verbose_name': '任务统计',
                'verbose_name_plural': '任务统计',
                'db_table': 'task_statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'status'], name='tasks_user_id_a53e17_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['zone', 'status'], name='tasks_zone_id_cdcc95_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'created_at'], name='tasks_status_655742_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['task', 'level'], name='task_logs_task_id_8914fc_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['task', 'created_at'], name='task_logs_task_id_e5a91c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskstatistics',
            unique_together={('zone', 'date', 'period_type')},
        ),
    ]
