# Generated by Django 5.2.10 on 2026-01-15 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='订单号')),
                ('amount', models.DecimalField(decimal_places=2, help_text='人民币', max_digits=10, verbose_name='订单金额(元)')),
                ('currency', models.CharField(default='CNY', max_length=10, verbose_name='货币单位')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, help_text='考虑优惠、折扣后的金额', max_digits=10, null=True, verbose_name='实际支付金额(元)')),
                ('order_type', models.CharField(help_text='如: recharge(充值), service_purchase(服务购买)', max_length=50, verbose_name='订单类型')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('processing', '处理中'), ('completed', '已完成'), ('cancelled', '已取消'), ('refunded', '已退款')], db_index=True, default='pending', max_length=20, verbose_name='订单状态')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='订单描述')),
                ('items', models.JSONField(blank=True, default=list, help_text='订单包含的商品/服务列表', verbose_name='订单项')),
                ('payment_method', models.CharField(blank=True, help_text='如: alipay, wechat, stripe', max_length=50, verbose_name='支付方式')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='支付单号')),
                ('gateway', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信支付'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=50, verbose_name='支付网关')),
                ('transaction_id', models.CharField(blank=True, max_length=200, verbose_name='第三方交易ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付金额(元)')),
                ('currency', models.CharField(default='CNY', max_length=10, verbose_name='货币单位')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('processing', '处理中'), ('success', '支付成功'), ('failed', '支付失败'), ('cancelled', '已取消'), ('refunded', '已退款')], db_index=True, default='pending', max_length=20, verbose_name='支付状态')),
                ('pay_url', models.URLField(blank=True, verbose_name='支付链接')),
                ('qr_code', models.TextField(blank=True, verbose_name='支付二维码')),
                ('notify_data', models.JSONField(blank=True, default=dict, help_text='第三方支付网关的回调数据', verbose_name='回调数据')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付完成时间')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='支付过期时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.order', verbose_name='关联订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('create', '创建'), ('query', '查询'), ('notify', '回调通知'), ('refund', '退款')], max_length=20, verbose_name='日志类型')),
                ('message', models.TextField(verbose_name='日志消息')),
                ('request_data', models.JSONField(blank=True, default=dict, verbose_name='请求数据')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='响应数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.payment', verbose_name='支付记录')),
            ],
            options={
                'verbose_name': '支付日志',
                'verbose_name_plural': '支付日志',
                'db_table': 'payment_logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_user_id_17dbdf_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_status_11db6c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type', 'status'], name='orders_order_t_4558a7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'status'], name='payments_order_i_3d4604_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='payments_user_id_1b771c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway', 'status'], name='payments_gateway_3ac0c5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_status_426d4f_idx'),
        ),
    ]
