# Generated by Django 5.0.1 on 2026-01-16 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(help_text='alipay, wechat, stripe, paypal, card_code', max_length=50, unique=True, verbose_name='支付网关')),
                ('name', models.CharField(max_length=100, verbose_name='显示名称')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('icon', models.CharField(blank=True, max_length=200, verbose_name='图标')),
                ('config_data', models.JSONField(blank=True, default=dict, help_text='存储API密钥等配置信息（加密）', verbose_name='配置数据')),
                ('fee_rate', models.DecimalField(decimal_places=4, default=0, help_text='0.0100 表示 1%', max_digits=5, verbose_name='手续费率')),
                ('min_amount', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='最小金额(元)')),
                ('max_amount', models.DecimalField(decimal_places=2, default=10000, max_digits=10, verbose_name='最大金额(元)')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '支付配置',
                'verbose_name_plural': '支付配置',
                'db_table': 'payment_configs',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, help_text='如: alipay, wechat, stripe, card_code', max_length=50, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信支付'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('card_code', '卡密充值')], max_length=50, verbose_name='支付网关'),
        ),
        migrations.CreateModel(
            name='RechargeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(db_index=True, help_text='充值卡密码', max_length=32, unique=True, verbose_name='卡密')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='面值(元)')),
                ('status', models.CharField(choices=[('unused', '未使用'), ('used', '已使用'), ('expired', '已过期'), ('disabled', '已禁用')], db_index=True, default='unused', max_length=20, verbose_name='卡密状态')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('batch_no', models.CharField(blank=True, db_index=True, help_text='批量生成时的批次标识', max_length=64, verbose_name='批次号')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recharge_cards', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_recharge_cards', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '充值卡密',
                'verbose_name_plural': '充值卡密',
                'db_table': 'recharge_cards',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'amount'], name='recharge_ca_status_8c8833_idx'), models.Index(fields=['batch_no'], name='recharge_ca_batch_n_b43df1_idx'), models.Index(fields=['created_by', 'created_at'], name='recharge_ca_created_dd08c3_idx')],
            },
        ),
    ]
