# Generated by Django 5.0.1 on 2026-01-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PluginState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='插件的唯一标识符', max_length=100, unique=True, verbose_name='插件名称')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否启用')),
                ('installed', models.BooleanField(default=False, verbose_name='是否已安装')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='插件的自定义配置', verbose_name='插件配置')),
                ('installed_at', models.DateTimeField(blank=True, null=True, verbose_name='安装时间')),
                ('enabled_at', models.DateTimeField(blank=True, null=True, verbose_name='启用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '插件状态',
                'verbose_name_plural': '插件状态',
                'db_table': 'plugin_states',
                'ordering': ['name'],
            },
        ),
    ]
