# Generated by Django 5.2.10 on 2026-01-17 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('google_accounts', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleBusinessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='配置键')),
                ('sheerid_enabled', models.BooleanField(default=True, verbose_name='启用SheerID验证')),
                ('gemini_enabled', models.BooleanField(default=True, verbose_name='启用Gemini订阅')),
                ('auto_verify', models.BooleanField(default=False, help_text='是否自动执行验证流程', verbose_name='自动验证')),
                ('settings', models.JSONField(default=dict, help_text='JSON格式的额外配置', verbose_name='其他设置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Google Business配置',
                'verbose_name_plural': 'Google Business配置',
                'db_table': 'google_business_config',
            },
        ),
        migrations.CreateModel(
            name='BusinessTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('sheerid_verify', 'SheerID验证'), ('gemini_subscribe', 'Gemini订阅'), ('account_setup', '账号设置')], max_length=20, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='执行时长(秒)')),
                ('result_data', models.JSONField(blank=True, default=dict, verbose_name='结果数据')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('screenshots', models.JSONField(blank=True, default=list, help_text='存储截图的路径或URL', verbose_name='截图列表')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('google_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_logs', to='google_accounts.googleaccount', verbose_name='Google账号')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_business_logs', to='tasks.task', verbose_name='关联任务')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_business_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Google Business任务日志',
                'verbose_name_plural': 'Google Business任务日志',
                'db_table': 'google_business_task_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='google_busi_user_id_7ed084_idx'), models.Index(fields=['google_account', 'task_type'], name='google_busi_google__7e817f_idx'), models.Index(fields=['status', 'created_at'], name='google_busi_status_3d5b19_idx')],
            },
        ),
    ]
