# Generated by Django 5.2.10 on 2026-01-17 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_accounts', '0001_initial'),
        ('google_business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCardInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(help_text='AES-256加密存储', max_length=500, verbose_name='卡号')),
                ('exp_month', models.CharField(max_length=10, verbose_name='过期月份')),
                ('exp_year', models.CharField(max_length=10, verbose_name='过期年份')),
                ('cvv', models.CharField(help_text='AES-256加密存储', max_length=500, verbose_name='CVV')),
                ('usage_count', models.IntegerField(default=0, verbose_name='已使用次数')),
                ('max_usage', models.IntegerField(default=1, help_text='一卡几绑', verbose_name='最大使用次数')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否激活')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_cards', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '卡信息',
                'verbose_name_plural': '卡信息',
                'db_table': 'google_cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoogleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('login', '登录'), ('get_link', '获取链接'), ('verify', 'SheerID验证'), ('bind_card', '绑卡订阅'), ('batch', '批量任务'), ('one_click', '一键到底')], max_length=20, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('paused', '已暂停'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('config', models.JSONField(default=dict, help_text='包含并发数、延迟、API Key等配置', verbose_name='任务配置')),
                ('total_count', models.IntegerField(default=0, verbose_name='总数量')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功数量')),
                ('failed_count', models.IntegerField(default=0, verbose_name='失败数量')),
                ('skipped_count', models.IntegerField(default=0, verbose_name='跳过数量')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Celery任务ID')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='预估费用')),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实际费用')),
                ('log', models.TextField(blank=True, verbose_name='任务日志')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_tasks', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Google任务',
                'verbose_name_plural': 'Google任务',
                'db_table': 'google_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoogleTaskAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('processing', '处理中'), ('success', '成功'), ('failed', '失败'), ('skipped', '跳过')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('result_message', models.TextField(blank=True, verbose_name='结果消息')),
                ('error_message', models.TextField(blank=True, verbose_name='错误消息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_business_task_relations', to='google_accounts.googleaccount', verbose_name='账号')),
                ('card_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_business.googlecardinfo', verbose_name='使用的卡')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_accounts', to='google_business.googletask', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务账号关联',
                'verbose_name_plural': '任务账号关联',
                'db_table': 'google_task_accounts',
            },
        ),
        migrations.AddIndex(
            model_name='googlecardinfo',
            index=models.Index(fields=['user', 'is_active'], name='google_card_user_id_cfec1e_idx'),
        ),
        migrations.AddIndex(
            model_name='googletask',
            index=models.Index(fields=['user', 'status'], name='google_task_user_id_c8c4cb_idx'),
        ),
        migrations.AddIndex(
            model_name='googletask',
            index=models.Index(fields=['celery_task_id'], name='google_task_celery__59dea8_idx'),
        ),
        migrations.AddIndex(
            model_name='googletask',
            index=models.Index(fields=['status', 'created_at'], name='google_task_status_ab34d7_idx'),
        ),
        migrations.AddIndex(
            model_name='googletaskaccount',
            index=models.Index(fields=['task', 'status'], name='google_task_task_id_35fbea_idx'),
        ),
        migrations.AddIndex(
            model_name='googletaskaccount',
            index=models.Index(fields=['account', 'status'], name='google_task_account_50cf9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='googletaskaccount',
            unique_together={('task', 'account')},
        ),
    ]
